DB_URL = "postgresql://neondb_owner:npg_GEh9VmqnRKp2@ep-red-bonus-ao19vjzt-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
GEMINI_API_KEY = "AIzaSyCJfIDZN9hNzqsxGA3u4sKYUgLGspFPmq8"
